### PR TITLE
Feat/data web controller

### PR DESCRIPTION
**Pull request by RapQor**

### CODE REVIEW

**Comment by RapQor** [comment]
ril, review ril

**Review by syhrlhyn834 — COMMENTED** [review]
Favico and Logo nya (image) simpen ke src

**Comment by syhrlhyn834** [comment]
> ril, review ril



> Favico and Logo nya (image) simpen ke src

Liat di postcontroller contohnya

**Comment by syhrlhyn834** [comment]
Update Controller store and update image nya, cek post controller terbaru sama main.go nya. Simpen di src/images aja semuanya

**Pull request merged**
